import { dirname } from 'node:path'
import { mkdir, writeFile } from 'node:fs/promises'
import { existsSync } from 'node:fs'

import type { DeclarationComponent } from './types'
import { stringifyTypeofImport } from './components'

export async function writeDeclaration(
  filepath: string | false,
  components: DeclarationComponent[],
) {
  if (!filepath || (!components.length && !existsSync(filepath))) return

  await mkdir(dirname(filepath), { recursive: true })
  await writeFile(filepath, getDeclaration(components, filepath), 'utf-8')
}

function getDeclaration(components: DeclarationComponent[], filepath: string) {
  const declarations = components
    .filter((component) => isIdentifier(component.as))
    .toSorted((a, b) => a.as.localeCompare(b.as))
    .map((component) => {
      return `  const ${component.as}: ${stringifyTypeofImport(component, filepath)}`
    })
    .join('\n')

  return `/* eslint-disable */
// @ts-nocheck
// oxlint-disable
// Generated by unplugin-svelte-comps
export {}

declare global {
${declarations}
}
`
}

function isIdentifier(value: string) {
  return /^[$A-Z_a-z][$\w]*$/.test(value)
}
